services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: gbit-technical-support
    container_name: gbit-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - gbit-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: gbit-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - gbit-network
    depends_on:
      - app

  vite:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: gbit-technical-support
    container_name: gbit-vite
    restart: unless-stopped
    working_dir: /var/www/
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    networks:
      - gbit-network

  worker:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: gbit-technical-support
    container_name: gbit-worker
    restart: unless-stopped
    working_dir: /var/www/
    command: sh /var/www/docker/start-worker.sh
    volumes:
      - ./:/var/www
    networks:
      - gbit-network
    depends_on:
      - app
      - db

  db:
    image: postgres:15
    container_name: gbit-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: 0YPw1FD6Yd4lN4Nt7qB1
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gbit-network

networks:
  gbit-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
